export const countries = {
  AF: { en_US: 'Afghanistan', pt_BR: 'Afeganistão' },
  AX: { en_US: 'Åland Islands', pt_BR: 'Ilhas Åland' },
  AL: { en_US: 'Albania', pt_BR: 'Albânia' },
  DZ: { en_US: 'Algeria', pt_BR: 'Argélia' },
  AS: { en_US: 'American Samoa', pt_BR: 'Samoa Americana' },
  AD: { en_US: 'AndorrA', pt_BR: 'Andorra' },
  AO: { en_US: 'Angola', pt_BR: 'Angola' },
  AI: { en_US: 'Anguilla', pt_BR: 'Anguilla' },
  AQ: { en_US: 'Antarctica', pt_BR: 'Antártida' },
  AG: { en_US: 'Antigua and Barbuda', pt_BR: 'Antígua e Barbuda' },
  AR: { en_US: 'Argentina', pt_BR: 'Argentina' },
  AM: { en_US: 'Armenia', pt_BR: 'Armênia' },
  AW: { en_US: 'Aruba', pt_BR: 'Aruba' },
  AU: { en_US: 'Australia', pt_BR: 'Austrália' },
  AT: { en_US: 'Austria', pt_BR: 'Áustria' },
  AZ: { en_US: 'Azerbaijan', pt_BR: 'Azerbaijão' },
  BS: { en_US: 'Bahamas', pt_BR: 'Bahamas' },
  BH: { en_US: 'Bahrain', pt_BR: 'Bahrein' },
  BD: { en_US: 'Bangladesh', pt_BR: 'Bangladesh' },
  BB: { en_US: 'Barbados', pt_BR: 'Barbados' },
  BY: { en_US: 'Belarus', pt_BR: 'Bielorrússia' },
  BE: { en_US: 'Belgium', pt_BR: 'Bélgica' },
  BZ: { en_US: 'Belize', pt_BR: 'Belize' },
  BJ: { en_US: 'Benin', pt_BR: 'Benin' },
  BM: { en_US: 'Bermuda', pt_BR: 'Bermudas' },
  BT: { en_US: 'Bhutan', pt_BR: 'Butão' },
  BO: { en_US: 'Bolivia', pt_BR: 'Bolívia' },
  BA: { en_US: 'Bosnia and Herzegovina', pt_BR: 'Bósnia e Herzegovina' },
  BW: { en_US: 'Botswana', pt_BR: 'Botsuana' },
  BV: { en_US: 'Bouvet Island', pt_BR: 'Ilha Bouvet' },
  BR: { en_US: 'Brazil', pt_BR: 'Brasil' },
  IO: {
    en_US: 'British Indian Ocean Territory',
    pt_BR: 'Território Britânico do Oceano Índico',
  },
  BN: { en_US: 'Brunei Darussalam', pt_BR: 'Brunei' },
  BG: { en_US: 'Bulgaria', pt_BR: 'Bulgária' },
  BF: { en_US: 'Burkina Faso', pt_BR: 'Burkina Faso' },
  BI: { en_US: 'Burundi', pt_BR: 'Burundi' },
  KH: { en_US: 'Cambodia', pt_BR: 'Camboja' },
  CM: { en_US: 'Cameroon', pt_BR: 'Camarões' },
  CA: { en_US: 'Canada', pt_BR: 'Canadá' },
  CV: { en_US: 'Cape Verde', pt_BR: 'Cabo Verde' },
  KY: { en_US: 'Cayman Islands', pt_BR: 'Ilhas Cayman' },
  CF: { en_US: 'Central African Republic', pt_BR: 'República Centro-Africana' },
  TD: { en_US: 'Chad', pt_BR: 'Chade' },
  CL: { en_US: 'Chile', pt_BR: 'Chile' },
  CN: { en_US: 'China', pt_BR: 'China' },
  CX: { en_US: 'Christmas Island', pt_BR: 'Ilha Christmas' },
  CC: { en_US: 'Cocos (Keeling) Islands', pt_BR: 'Ilhas Cocos (Keeling)' },
  CO: { en_US: 'Colombia', pt_BR: 'Colômbia' },
  KM: { en_US: 'Comoros', pt_BR: 'Comores' },
  CG: { en_US: 'Congo', pt_BR: 'Congo' },
  CD: {
    en_US: 'Congo, The Democratic Republic of the',
    pt_BR: 'República Democrática do Congo',
  },
  CK: { en_US: 'Cook Islands', pt_BR: 'Ilhas Cook' },
  CR: { en_US: 'Costa Rica', pt_BR: 'Costa Rica' },
  CI: { en_US: "Cote D'Ivoire", pt_BR: 'Costa do Marfim' },
  HR: { en_US: 'Croatia', pt_BR: 'Croácia' },
  CU: { en_US: 'Cuba', pt_BR: 'Cuba' },
  CY: { en_US: 'Cyprus', pt_BR: 'Chipre' },
  CZ: { en_US: 'Czech Republic', pt_BR: 'República Tcheca' },
  DK: { en_US: 'Denmark', pt_BR: 'Dinamarca' },
  DJ: { en_US: 'Djibouti', pt_BR: 'Djibuti' },
  DM: { en_US: 'Dominica', pt_BR: 'Dominica' },
  DO: { en_US: 'Dominican Republic', pt_BR: 'República Dominicana' },
  EC: { en_US: 'Ecuador', pt_BR: 'Equador' },
  EG: { en_US: 'Egypt', pt_BR: 'Egito' },
  SV: { en_US: 'El Salvador', pt_BR: 'El Salvador' },
  GQ: { en_US: 'Equatorial Guinea', pt_BR: 'Guiné Equatorial' },
  ER: { en_US: 'Eritrea', pt_BR: 'Eritreia' },
  EE: { en_US: 'Estonia', pt_BR: 'Estônia' },
  ET: { en_US: 'Ethiopia', pt_BR: 'Etiópia' },
  FK: {
    en_US: 'Falkland Islands (Malvinas)',
    pt_BR: 'Ilhas Falkland (Malvinas)',
  },
  FO: { en_US: 'Faroe Islands', pt_BR: 'Ilhas Faroé' },
  FJ: { en_US: 'Fiji', pt_BR: 'Fiji' },
  FI: { en_US: 'Finland', pt_BR: 'Finlândia' },
  FR: { en_US: 'France', pt_BR: 'França' },
  GF: { en_US: 'French Guiana', pt_BR: 'Guiana Francesa' },
  PF: { en_US: 'French Polynesia', pt_BR: 'Polinésia Francesa' },
  TF: {
    en_US: 'French Southern Territories',
    pt_BR: 'Territórios Franceses do Sul',
  },
  GA: { en_US: 'Gabon', pt_BR: 'Gabão' },
  GM: { en_US: 'Gambia', pt_BR: 'Gâmbia' },
  GE: { en_US: 'Georgia', pt_BR: 'Geórgia' },
  DE: { en_US: 'Germany', pt_BR: 'Alemanha' },
  GH: { en_US: 'Ghana', pt_BR: 'Gana' },
  GI: { en_US: 'Gibraltar', pt_BR: 'Gibraltar' },
  GR: { en_US: 'Greece', pt_BR: 'Grécia' },
  GL: { en_US: 'Greenland', pt_BR: 'Groenlândia' },
  GD: { en_US: 'Grenada', pt_BR: 'Granada' },
  GP: { en_US: 'Guadeloupe', pt_BR: 'Guadalupe' },
  GU: { en_US: 'Guam', pt_BR: 'Guam' },
  GT: { en_US: 'Guatemala', pt_BR: 'Guatemala' },
  GG: { en_US: 'Guernsey', pt_BR: 'Guernsey' },
  GN: { en_US: 'Guinea', pt_BR: 'Guiné' },
  GW: { en_US: 'Guinea-Bissau', pt_BR: 'Guiné-Bissau' },
  GY: { en_US: 'Guyana', pt_BR: 'Guiana' },
  HT: { en_US: 'Haiti', pt_BR: 'Haiti' },
  HM: {
    en_US: 'Heard Island and Mcdonald Islands',
    pt_BR: 'Ilha Heard e Ilhas McDonald',
  },
  VA: {
    en_US: 'Holy See (Vatican City State)',
    pt_BR: 'Santa Sé (Estado da Cidade do Vaticano)',
  },
  HN: { en_US: 'Honduras', pt_BR: 'Honduras' },
  HK: { en_US: 'Hong Kong', pt_BR: 'Hong Kong' },
  HU: { en_US: 'Hungary', pt_BR: 'Hungria' },
  IS: { en_US: 'Iceland', pt_BR: 'Islândia' },
  IN: { en_US: 'India', pt_BR: 'Índia' },
  ID: { en_US: 'Indonesia', pt_BR: 'Indonésia' },
  IR: { en_US: 'Iran, Islamic Republic Of', pt_BR: 'Irã' },
  IQ: { en_US: 'Iraq', pt_BR: 'Iraque' },
  IE: { en_US: 'Ireland', pt_BR: 'Irlanda' },
  IM: { en_US: 'Isle of Man', pt_BR: 'Ilha de Man' },
  IL: { en_US: 'Israel', pt_BR: 'Israel' },
  IT: { en_US: 'Italy', pt_BR: 'Itália' },
  JM: { en_US: 'Jamaica', pt_BR: 'Jamaica' },
  JP: { en_US: 'Japan', pt_BR: 'Japão' },
  JE: { en_US: 'Jersey', pt_BR: 'Jersey' },
  JO: { en_US: 'Jordan', pt_BR: 'Jordânia' },
  KZ: { en_US: 'Kazakhstan', pt_BR: 'Cazaquistão' },
  KE: { en_US: 'Kenya', pt_BR: 'Quênia' },
  KI: { en_US: 'Kiribati', pt_BR: 'Kiribati' },
  KP: {
    en_US: "Korea, Democratic People'S Republic of",
    pt_BR: 'Coreia do Norte',
  },
  KR: { en_US: 'Korea, Republic of', pt_BR: 'Coreia do Sul' },
  KW: { en_US: 'Kuwait', pt_BR: 'Kuwait' },
  KG: { en_US: 'Kyrgyzstan', pt_BR: 'Quirguistão' },
  LA: { en_US: "Lao People'S Democratic Republic", pt_BR: 'Laos' },
  LV: { en_US: 'Latvia', pt_BR: 'Letônia' },
  LB: { en_US: 'Lebanon', pt_BR: 'Líbano' },
  LS: { en_US: 'Lesotho', pt_BR: 'Lesoto' },
  LR: { en_US: 'Liberia', pt_BR: 'Libéria' },
  LY: { en_US: 'Libyan Arab Jamahiriya', pt_BR: 'Líbia' },
  LI: { en_US: 'Liechtenstein', pt_BR: 'Liechtenstein' },
  LT: { en_US: 'Lithuania', pt_BR: 'Lituânia' },
  LU: { en_US: 'Luxembourg', pt_BR: 'Luxemburgo' },
  MO: { en_US: 'Macao', pt_BR: 'Macau' },
  MK: {
    en_US: 'Macedonia, The Former Yugoslav Republic of',
    pt_BR: 'Macedônia',
  },
  MG: { en_US: 'Madagascar', pt_BR: 'Madagascar' },
  MW: { en_US: 'Malawi', pt_BR: 'Malawi' },
  MY: { en_US: 'Malaysia', pt_BR: 'Malásia' },
  MV: { en_US: 'Maldives', pt_BR: 'Maldivas' },
  ML: { en_US: 'Mali', pt_BR: 'Mali' },
  MT: { en_US: 'Malta', pt_BR: 'Malta' },
  MH: { en_US: 'Marshall Islands', pt_BR: 'Ilhas Marshall' },
  MQ: { en_US: 'Martinique', pt_BR: 'Martinica' },
  MR: { en_US: 'Mauritania', pt_BR: 'Mauritânia' },
  MU: { en_US: 'Mauritius', pt_BR: 'Maurício' },
  YT: { en_US: 'Mayotte', pt_BR: 'Mayotte' },
  MX: { en_US: 'Mexico', pt_BR: 'México' },
  FM: { en_US: 'Micronesia, Federated States of', pt_BR: 'Micronésia' },
  MD: { en_US: 'Moldova, Republic of', pt_BR: 'Moldávia' },
  MC: { en_US: 'Monaco', pt_BR: 'Mônaco' },
  MN: { en_US: 'Mongolia', pt_BR: 'Mongólia' },
  MS: { en_US: 'Montserrat', pt_BR: 'Montserrat' },
  MA: { en_US: 'Morocco', pt_BR: 'Marrocos' },
  MZ: { en_US: 'Mozambique', pt_BR: 'Moçambique' },
  MM: { en_US: 'Myanmar', pt_BR: 'Mianmar' },
  NA: { en_US: 'Namibia', pt_BR: 'Namíbia' },
  NR: { en_US: 'Nauru', pt_BR: 'Nauru' },
  NP: { en_US: 'Nepal', pt_BR: 'Nepal' },
  NL: { en_US: 'Netherlands', pt_BR: 'Países Baixos' },
  AN: { en_US: 'Netherlands Antilles', pt_BR: 'Antilhas Holandesas' },
  NC: { en_US: 'New Caledonia', pt_BR: 'Nova Caledônia' },
  NZ: { en_US: 'New Zealand', pt_BR: 'Nova Zelândia' },
  NI: { en_US: 'Nicaragua', pt_BR: 'Nicarágua' },
  NE: { en_US: 'Niger', pt_BR: 'Níger' },
  NG: { en_US: 'Nigeria', pt_BR: 'Nigéria' },
  NU: { en_US: 'Niue', pt_BR: 'Niue' },
  NF: { en_US: 'Norfolk Island', pt_BR: 'Ilha Norfolk' },
  MP: { en_US: 'Northern Mariana Islands', pt_BR: 'Ilhas Marianas do Norte' },
  NO: { en_US: 'Norway', pt_BR: 'Noruega' },
  OM: { en_US: 'Oman', pt_BR: 'Omã' },
  PK: { en_US: 'Pakistan', pt_BR: 'Paquistão' },
  PW: { en_US: 'Palau', pt_BR: 'Palau' },
  PS: {
    en_US: 'Palestinian Territory, Occupied',
    pt_BR: 'Território Palestino Ocupado',
  },
  PA: { en_US: 'Panama', pt_BR: 'Panamá' },
  PG: { en_US: 'Papua New Guinea', pt_BR: 'Papua-Nova Guiné' },
  PY: { en_US: 'Paraguay', pt_BR: 'Paraguai' },
  PE: { en_US: 'Peru', pt_BR: 'Peru' },
  PH: { en_US: 'Philippines', pt_BR: 'Filipinas' },
  PN: { en_US: 'Pitcairn', pt_BR: 'Pitcairn' },
  PL: { en_US: 'Poland', pt_BR: 'Polônia' },
  PT: { en_US: 'Portugal', pt_BR: 'Portugal' },
  PR: { en_US: 'Puerto Rico', pt_BR: 'Porto Rico' },
  QA: { en_US: 'Qatar', pt_BR: 'Catar' },
  RE: { en_US: 'Reunion', pt_BR: 'Reunião' },
  RO: { en_US: 'Romania', pt_BR: 'Romênia' },
  RU: { en_US: 'Russian Federation', pt_BR: 'Federação Russa' },
  RW: { en_US: 'RWANDA', pt_BR: 'Ruanda' },
  SH: { en_US: 'Saint Helena', pt_BR: 'Santa Helena' },
  KN: { en_US: 'Saint Kitts and Nevis', pt_BR: 'São Cristóvão e Nevis' },
  LC: { en_US: 'Saint Lucia', pt_BR: 'Santa Lúcia' },
  PM: { en_US: 'Saint Pierre and Miquelon', pt_BR: 'São Pedro e Miquelon' },
  VC: {
    en_US: 'Saint Vincent and the Grenadines',
    pt_BR: 'São Vicente e Granadinas',
  },
  WS: { en_US: 'Samoa', pt_BR: 'Samoa' },
  SM: { en_US: 'San Marino', pt_BR: 'San Marino' },
  ST: { en_US: 'Sao Tome and Principe', pt_BR: 'São Tomé e Príncipe' },
  SA: { en_US: 'Saudi Arabia', pt_BR: 'Arábia Saudita' },
  SN: { en_US: 'Senegal', pt_BR: 'Senegal' },
  CS: { en_US: 'Serbia and Montenegro', pt_BR: 'Sérvia e Montenegro' },
  SC: { en_US: 'Seychelles', pt_BR: 'Seychelles' },
  SL: { en_US: 'Sierra Leone', pt_BR: 'Serra Leoa' },
  SG: { en_US: 'Singapore', pt_BR: 'Singapura' },
  SK: { en_US: 'Slovakia', pt_BR: 'Eslováquia' },
  SI: { en_US: 'Slovenia', pt_BR: 'Eslovênia' },
  SB: { en_US: 'Solomon Islands', pt_BR: 'Ilhas Salomão' },
  SO: { en_US: 'Somalia', pt_BR: 'Somália' },
  ZA: { en_US: 'South Africa', pt_BR: 'África do Sul' },
  GS: {
    en_US: 'South Georgia and the South Sandwich Islands',
    pt_BR: 'Geórgia do Sul e Ilhas Sandwich do Sul',
  },
  ES: { en_US: 'Spain', pt_BR: 'Espanha' },
  LK: { en_US: 'Sri Lanka', pt_BR: 'Sri Lanka' },
  SD: { en_US: 'Sudan', pt_BR: 'Sudão' },
  SR: { en_US: 'Suriname', pt_BR: 'Suriname' },
  SJ: { en_US: 'Svalbard and Jan Mayen', pt_BR: 'Svalbard e Jan Mayen' },
  SZ: { en_US: 'Swaziland', pt_BR: 'Suazilândia' },
  SE: { en_US: 'Sweden', pt_BR: 'Suécia' },
  CH: { en_US: 'Switzerland', pt_BR: 'Suíça' },
  SY: { en_US: 'Syrian Arab Republic', pt_BR: 'Síria' },
  TW: { en_US: 'Taiwan, Province of China', pt_BR: 'Taiwan' },
  TJ: { en_US: 'Tajikistan', pt_BR: 'Tajiquistão' },
  TZ: { en_US: 'Tanzania, United Republic of', pt_BR: 'Tanzânia' },
  TH: { en_US: 'Thailand', pt_BR: 'Tailândia' },
  TL: { en_US: 'Timor-Leste', pt_BR: 'Timor-Leste' },
  TG: { en_US: 'Togo', pt_BR: 'Togo' },
  TK: { en_US: 'Tokelau', pt_BR: 'Tokelau' },
  TO: { en_US: 'Tonga', pt_BR: 'Tonga' },
  TT: { en_US: 'Trinidad and Tobago', pt_BR: 'Trinidad e Tobago' },
  TN: { en_US: 'Tunisia', pt_BR: 'Tunísia' },
  TR: { en_US: 'Turkey', pt_BR: 'Turquia' },
  TM: { en_US: 'Turkmenistan', pt_BR: 'Turcomenistão' },
  TC: { en_US: 'Turks and Caicos Islands', pt_BR: 'Ilhas Turks e Caicos' },
  TV: { en_US: 'Tuvalu', pt_BR: 'Tuvalu' },
  UG: { en_US: 'Uganda', pt_BR: 'Uganda' },
  UA: { en_US: 'Ukraine', pt_BR: 'Ucrânia' },
  AE: { en_US: 'United Arab Emirates', pt_BR: 'Emirados Árabes Unidos' },
  GB: { en_US: 'United Kingdom', pt_BR: 'Reino Unido' },
  US: { en_US: 'United States', pt_BR: 'Estados Unidos' },
  UM: {
    en_US: 'United States Minor Outlying Islands',
    pt_BR: 'Ilhas Menores Distantes dos Estados Unidos',
  },
  UY: { en_US: 'Uruguay', pt_BR: 'Uruguai' },
  UZ: { en_US: 'Uzbekistan', pt_BR: 'Uzbequistão' },
  VU: { en_US: 'Vanuatu', pt_BR: 'Vanuatu' },
  VE: { en_US: 'Venezuela', pt_BR: 'Venezuela' },
  VN: { en_US: 'Viet Nam', pt_BR: 'Vietnã' },
  VG: { en_US: 'Virgin Islands, British', pt_BR: 'Ilhas Virgens Britânicas' },
  VI: { en_US: 'Virgin Islands, U.S.', pt_BR: 'Ilhas Virgens Americanas' },
  WF: { en_US: 'Wallis and Futuna', pt_BR: 'Wallis e Futuna' },
  EH: { en_US: 'Western Sahara', pt_BR: 'Saara Ocidental' },
  YE: { en_US: 'Yemen', pt_BR: 'Iêmen' },
  ZM: { en_US: 'Zambia', pt_BR: 'Zâmbia' },
  ZW: { en_US: 'Zimbabwe', pt_BR: 'Zimbábue' },
}
